setgut 11-1.gut scrs\11-1.gut 11 1 游戏开始
setgut 11-2.gut scrs\11-2.gut 11 2 游戏开始
setgut 11-3.gut scrs\11-3.gut 11 3 游戏开始
setgut 11-4.gut scrs\11-4.gut 11 4 游戏开始
setgut 11-5.gut scrs\11-5.gut 11 5 游戏开始
setgut 11-6.gut scrs\11-6.gut 11 6 游戏开始
setgut 11-7.gut scrs\11-7.gut 11 7 游戏开始
pause
setgut 11-8.gut scrs\11-8.gut 11 8 游戏开始
setgut 11-9.gut scrs\11-9.gut 11 9 游戏开始
setgut 11-10.gut scrs\11-10.gut 11 10 游戏开始