setgut 14-1.gut scrs\14-1.gut 14 1 游戏开始
setgut 14-2.gut scrs\14-2.gut 14 2 游戏开始
setgut 14-3.gut scrs\14-3.gut 14 3 游戏开始
setgut 14-4.gut scrs\14-4.gut 14 4 游戏开始
setgut 14-5.gut scrs\14-5.gut 14 5 游戏开始
setgut 14-6.gut scrs\14-6.gut 14 6 游戏开始
setgut 14-7.gut scrs\14-7.gut 14 7 游戏开始
pause
setgut 14-8.gut scrs\14-8.gut 14 8 游戏开始
setgut 14-9.gut scrs\14-9.gut 14 9 游戏开始
setgut 14-10.gut scrs\14-10.gut 14 10 游戏开始
setgut 14-11.gut scrs\14-11.gut 14 11 游戏开始