setgut 5-1.gut scrs\5-1.gut 5 1 游戏开始
setgut 5-2.gut scrs\5-2.gut 5 2 游戏开始
setgut 5-3.gut scrs\5-3.gut 5 3 游戏开始
setgut 5-4.gut scrs\5-4.gut 5 4 游戏开始
setgut 5-5.gut scrs\5-5.gut 5 5 游戏开始
setgut 5-6.gut scrs\5-6.gut 5 6 游戏开始
setgut 5-7.gut scrs\5-7.gut 5 7 游戏开始
pause
setgut 5-8.gut scrs\5-8.gut 5 8 游戏开始
setgut 5-9.gut scrs\5-9.gut 5 9 游戏开始
setgut 5-10.gut scrs\5-10.gut 5 10 游戏开始
setgut 5-11.gut scrs\5-11.gut 5 11 游戏开始
setgut 5-12.gut scrs\5-12.gut 5 12 游戏开始
setgut 5-13.gut scrs\5-13.gut 5 13 游戏开始
pause
setgut 5-14.gut scrs\5-14.gut 5 14 游戏开始
setgut 5-15.gut scrs\5-15.gut 5 15 游戏开始
setgut 5-16.gut scrs\5-16.gut 5 16 游戏开始
setgut 5-17.gut scrs\5-17.gut 5 17 游戏开始
setgut 5-18.gut scrs\5-18.gut 5 18 游戏开始
setgut 5-19.gut scrs\5-19.gut 5 19 游戏开始
pause
setgut 5-20.gut scrs\5-20.gut 5 20 游戏开始
setgut 5-21.gut scrs\5-21.gut 5 21 游戏开始