setgut 6-1.gut scrs\6-1.gut 6 1 游戏开始
setgut 6-2.gut scrs\6-2.gut 6 2 游戏开始
setgut 6-3.gut scrs\6-3.gut 6 3 游戏开始
setgut 6-4.gut scrs\6-4.gut 6 4 游戏开始
setgut 6-5.gut scrs\6-5.gut 6 5 游戏开始
setgut 6-6.gut scrs\6-6.gut 6 6 游戏开始
setgut 6-7.gut scrs\6-7.gut 6 7 游戏开始
pause
setgut 6-8.gut scrs\6-8.gut 6 8 游戏开始
setgut 6-9.gut scrs\6-9.gut 6 9 游戏开始
setgut 6-10.gut scrs\6-10.gut 6 10 游戏开始
setgut 6-11.gut scrs\6-11.gut 6 11 游戏开始
setgut 6-12.gut scrs\6-12.gut 6 12 游戏开始
setgut 6-13.gut scrs\6-13.gut 6 13 游戏开始
setgut 6-14.gut scrs\6-14.gut 6 14 游戏开始