setgut 7-1.gut scrs\7-1.gut 7 1 游戏开始
setgut 7-2.gut scrs\7-2.gut 7 2 游戏开始
setgut 7-3.gut scrs\7-3.gut 7 3 游戏开始
setgut 7-4.gut scrs\7-4.gut 7 4 游戏开始
setgut 7-5.gut scrs\7-5.gut 7 5 游戏开始
setgut 7-6.gut scrs\7-6.gut 7 6 游戏开始
setgut 7-7.gut scrs\7-7.gut 7 7 游戏开始
pause
setgut 7-8.gut scrs\7-8.gut 7 8 游戏开始
setgut 7-9.gut scrs\7-9.gut 7 9 游戏开始
setgut 7-10.gut scrs\7-10.gut 7 10 游戏开始
setgut 7-11.gut scrs\7-11.gut 7 11 游戏开始
setgut 7-12.gut scrs\7-12.gut 7 12 游戏开始
setgut 7-13.gut scrs\7-13.gut 7 13 游戏开始
setgut 7-14.gut scrs\7-14.gut 7 14 游戏开始