setgut 8-1.gut scrs\8-1.gut 8 1 游戏开始
setgut 8-2.gut scrs\8-2.gut 8 2 游戏开始
setgut 8-3.gut scrs\8-3.gut 8 3 游戏开始
setgut 8-4.gut scrs\8-4.gut 8 4 游戏开始
setgut 8-5.gut scrs\8-5.gut 8 5 游戏开始
setgut 8-6.gut scrs\8-6.gut 8 6 游戏开始
setgut 8-7.gut scrs\8-7.gut 8 7 游戏开始
pause
setgut 8-8.gut scrs\8-8.gut 8 8 游戏开始
setgut 8-9.gut scrs\8-9.gut 8 9 游戏开始
setgut 8-10.gut scrs\8-10.gut 8 10 游戏开始
setgut 8-11.gut scrs\8-11.gut 8 11 游戏开始
setgut 8-12.gut scrs\8-12.gut 8 12 游戏开始