setgut 9-1.gut scrs\9-1.gut 9 1 游戏开始
setgut 9-2.gut scrs\9-2.gut 9 2 游戏开始
setgut 9-3.gut scrs\9-3.gut 9 3 游戏开始
setgut 9-4.gut scrs\9-4.gut 9 4 游戏开始
setgut 9-5.gut scrs\9-5.gut 9 5 游戏开始
setgut 9-6.gut scrs\9-6.gut 9 6 游戏开始
setgut 9-7.gut scrs\9-7.gut 9 7 游戏开始
pause
setgut 9-8.gut scrs\9-8.gut 9 8 游戏开始
setgut 9-9.gut scrs\9-9.gut 9 9 游戏开始
setgut 9-10.gut scrs\9-10.gut 9 10 游戏开始
setgut 9-11.gut scrs\9-11.gut 9 11 游戏开始
setgut 9-12.gut scrs\9-12.gut 9 12 游戏开始
setgut 9-13.gut scrs\9-13.gut 9 13 游戏开始
setgut 9-14.gut scrs\9-14.gut 9 14 游戏开始