
setgut 1-1.gut scrs\1-1.gut 1 1 游戏开始
setgut 1-2.gut scrs\1-2.gut 1 2 游戏开始
setgut 1-3.gut scrs\1-3.gut 1 3 游戏开始
setgut 1-4.gut scrs\1-4.gut 1 4 游戏开始
setgut 1-5.gut scrs\1-5.gut 1 5 游戏开始
setgut 2-1m1-1.gut scrs\2-1.gut 2 1 游戏开始
setgut 2-2m2-7.gut scrs\2-2.gut 2 2 游戏开始
setgut 2-3m2-9.gut scrs\2-3.gut 2 3 游戏开始
setgut 2-4m2-6.gut scrs\2-4.gut 2 4 游戏开始
setgut 2-5m2-1.gut scrs\2-5.gut 2 5 游戏开始
setgut 2-6m2-4.gut scrs\2-6.gut 2 6 游戏开始
setgut 2-7m2-2.gut scrs\2-7.gut 2 7 游戏开始
pause
setgut 2-8m2-4.gut scrs\2-8.gut 2  8 游戏开始
setgut 2-10m2-3.gut scrs\2-10.gut 2 10 游戏开始
setgut 2-11m2-5.gut scrs\2-11.gut 2 11 游戏开始
setgut 2-12m1-2.gut scrs\2-12.gut 2 12 游戏开始
setgut 2-13m1-3.gut scrs\2-13.gut 2 13 游戏开始
setgut 2-14m1-7.gut scrs\2-14.gut 2 14 游戏开始
setgut 2-15m1-4.gut scrs\2-15.gut 2 15 游戏开始
pause
setgut 2-16m1-5.gut scrs\2-16.gut 2 16 游戏开始
setgut 2-17m1-6.gut scrs\2-17.gut 2 17 游戏开始
setgut 2-18m3-1.gut scrs\2-18.gut 2 18 游戏开始
setgut 2-19m3-2.gut scrs\2-19.gut 2 19 游戏开始
setgut 2-20m3-3.gut scrs\2-20.gut 2 20 游戏开始
setgut 2-21m3-4.gut scrs\2-21.gut 2 21 游戏开始
setgut 2-22m3-5.gut scrs\2-22.gut 2 22 游戏开始
pause
setgut 2-23m3-2.gut scrs\2-23.gut 2 23 游戏开始
setgut 2-24m3-3.gut scrs\2-24.gut 2 24 游戏开始
setgut 2-25m3-4.gut scrs\2-25.gut 2 25 游戏开始
setgut 2-26m3-5.gut scrs\2-26.gut 2 26 游戏开始
setgut 2-31.gut scrs\2-31.gut 2 31 游戏开始
setgut 2-32.gut scrs\2-32.gut 2 32 游戏开始
setgut 2-33.gut scrs\2-33.gut 2 33 游戏开始
setgut 2-34.gut scrs\2-34.gut 2 34 游戏开始
pause
setgut 2-35.gut scrs\2-35.gut 2 35 游戏开始
setgut 2-36.gut scrs\2-36.gut 2 36 游戏开始
setgut 2-37.gut scrs\2-37.gut 2 37 游戏开始
setgut 2-38.gut scrs\2-38.gut 2 38 游戏开始
setgut 2-39.gut scrs\2-39.gut 2 39 游戏开始
setgut 2-40.gut scrs\2-40.gut 2 40 游戏开始
setgut 2-41.gut scrs\2-41.gut 2 41 游戏开始
pause
setgut 2-42.gut scrs\2-42.gut 2 42 游戏开始
setgut 2-43.gut scrs\2-43.gut 2 43 游戏开始
setgut 2-44.gut scrs\2-44.gut 2 44 游戏开始
setgut 2-45.gut scrs\2-45.gut 2 45 游戏开始
setgut 2-46.gut scrs\2-46.gut 2 46 游戏开始
setgut 2-48.gut scrs\2-48.gut 2 48 游戏开始
setgut 2-49.gut scrs\2-49.gut 2 49 游戏开始
pause
setgut 2-50.gut scrs\2-50.gut 2 50 游戏开始
setgut 2-51.gut scrs\2-51.gut 2 51 游戏开始
setgut 2-52.gut scrs\2-52.gut 2 52 游戏开始
setgut 2-53.gut scrs\2-53.gut 2 53 游戏开始
setgut 3-1.gut scrs\3-1.gut 3 1 游戏开始
setgut 5-1.gut scrs\5-1.gut 5 1 游戏开始
pause
setgut 3-2.gut scrs\3-2.gut 3 2 游戏开始
setgut 3-3.gut scrs\3-3.gut 3 3 游戏开始
setgut 3-4.gut scrs\3-4.gut 3 4 游戏开始
setgut 3-5.gut scrs\3-5.gut 3 5 游戏开始
setgut 3-6.gut scrs\3-6.gut 3 6 游戏开始
setgut 3-7.gut scrs\3-7.gut 3 7 游戏开始
pause
setgut 3-8.gut scrs\3-8.gut 3 8 游戏开始
setgut 3-9.gut scrs\3-9.gut 3 9 游戏开始
setgut 3-10.gut scrs\3-10.gut 3 10 游戏开始
setgut 3-11.gut scrs\3-11.gut 3 11 游戏开始
setgut 3-12.gut scrs\3-12.gut 3 12 游戏开始
setgut 3-13.gut scrs\3-13.gut 3 13 游戏开始